### PR TITLE
Restructure default ui

### PR DESCRIPTION
**Pull request by stefpiatek**
Based on chat with Patrick the main feedback from scientists was 

- reordering of tabs (basically the only change in UI)
- show correct CNV by default
- show correct sample and gene in coverage by default

Also used `global.R` (run once by shiny on app load) and a function to get metadata so we don't get loads of variables that appear out of nowhere. 

# Required changes for implementation.

I'm happy to do these next week, but just to keep track. 

- [x] GOSHG2P will need to also create the metadata.csv file, example file is [Linux/shinyGUI/metadata.csv.EXAMPLE](https://github.com/pdl30/DECoN/blob/restructure_default_ui/Linux/shinyGUI/metadata.csv.EXAMPLE)
- [x] GOSHG2P will need to call runShiny.R adding in the metadata argument

# Other points

There are some warnings that you get when the app is loading, but the plots then render. Could look into this but doesn't seem super worth it

### CODE REVIEW

**Review by pdl30 — APPROVED** [review]
The changes look good, do you have an example of a running instance?

**Comment by stefpiatek** [comment]
> The changes look good, do you have an example of a running instance?

Only locally, but can set up some data and get one running somewhere accessible - where would be best?

**Comment by stefpiatek** [comment]
Decided to merge the updated branch into this PR, turns out it broke some things!

Shouldn't have been as painful to fix as it was, but at least I could run it locally with a debugger. Running instance <http://10.101.84.106:5888/> with the following settings
```python
{"run_name": "200515_NB501996_0543_AHNTKGBGXF_Cancer_v2",
"cnv_id": 2,
"sample_name": "18G14432_PE_sorted",
"gene_name": "PMS2"}
```

Enjoy

**Review by nikitapov — APPROVED** [review]
Just checked the running instance, looks good! Happy for it to be merged.

**Pull request merged**
